# Generated by Django 5.1.7 on 2025-03-29 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date and time of game')),
                ('player_1_rating', models.IntegerField()),
                ('player_2_rating', models.IntegerField()),
                ('player_1_rating_change', models.IntegerField()),
                ('player_2_rating_change', models.IntegerField()),
                ('gameResult', models.IntegerField(choices=[(1, 'Player 1 Wins'), (2, 'Player 2 Wins'), (3, 'Draw')])),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_games_set', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_games_set', to=settings.AUTH_USER_MODEL)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_games_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
