# Generated by Django 5.1.7 on 2025-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_rename_gameresult_game_game_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rating_deviation', models.FloatField()),
                ('rating_volatility', models.FloatField()),
            ],
        ),
    ]
