# Generated by Django 5.1.7 on 2025-03-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_rating_id_rating_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_deviation',
            field=models.FloatField(default=350),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_volatility',
            field=models.FloatField(default=0.06),
        ),
    ]
