# Generated by Django 5.1.7 on 2025-03-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_game_ranked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('can_view_others_games', 'Can view the games of other players. This permission is required to view the registry.'), ('can_add_games', 'Can add new games to the registry.')]},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'permissions': [('can_view_others_ratings', 'Can view the ratings of other players.')]},
        ),
    ]
