# Generated by Django 5.1.7 on 2025-05-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_officers_list', 'Can view the list of officer. Captains should have this permission.'), ('can_manage_officer_status', 'Can give or revoke the officer status from users. Captains should have this permission.')]},
        ),
    ]
