# Generated by Django 5.1.7 on 2025-05-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_officers_list', 'Can view the list of officer. Captains should have this permission.'), ('can_manage_officer_status', 'Can give or revoke the officer status from users. Captains should have this permission.'), ('eligible_to_be_officer', 'Is eligible to become an officer. Regular users should be eligible, but not current officers or captains.')]},
        ),
    ]
