# Generated by Django 5.1.7 on 2025-08-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_officers_list', 'Can view the list of officer. Captains should have this permission.'), ('can_manage_officer_status', 'Can give or revoke the officer status from users. Captains should have this permission.'), ('eligible_to_be_officer', 'Is eligible to become an officer. Regular users should be eligible, but not current officers or captains.'), ('able_to_be_demoted_as_officer', 'Is able to be demoted as an officer. Officers should have this permission.'), ('able_to_be_demoted_as_captain', 'Is able to be demoted as a captain. Captains should have this permission.'), ('eligible_to_be_captain', 'Is eligible to become a captain. Only officers should be eligible.'), ('can_manage_captain_status', 'Can give or revoke captain status from users. Only the president should have this permission')]},
        ),
    ]
